# Rule W016
---
- name: Example playbook
  hosts: all

  tasks:
    - name: Install python and go
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
        with_items:
          - python
          - go
