# Rule W011
---
- name: Example playbook
  hosts: all

  tasks:
    - name: A task with old loop style
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ items |flatten(levels=1) }}"
