# Rule W021 - Replace apt, dnf, and yum with package module
---
- name: Example playbook
  hosts: all

  tasks:
    - name: Install python
      ansible.builtin.package:
        name: "{{ user_packages }}"
        state: present

    - name: Install go
      ansible.builtin.package:
        name: "{{ user_packages }}"
        state: present

    - name: Install Apache
      ansible.builtin.package:
        name: "{{ user_packages }}"
        state: present
